export const NAVER_SELECTORS = {
  saveButtons: [
    '.btn_save',
    '#btn_save',
    '[data-name="save"]',
    '.se-toolbar-save-button',
    '.se-save-button',
    'button[class*="save_btn"]',
    '[class*="save_btn"]',
    'button[title*="저장"]',
    'button[aria-label*="저장"]',
  ],
  toast: [
    '[class*="toast"]',
    '[class*="snackbar"]',
    '[role="alert"]',
    '[class*="notification"]',
    '[class*="message"]',
  ],
  spinner: [
    '[class*="saving"]',
    '[class*="save_ing"]',
    '[class*="spinner"]',
    '[class*="loading"]',
    '.se-progress',
    '.se-progress-bar',
  ],
  overlay: [
    '.se-popup-dim',
    '.se-popup-dim-transparent',
    '[class*="dimmed"]',
    '[class*="overlay"]',
    '[role="dialog"]',
    '.ReactModal__Overlay',
  ],
  sessionBlocked: [
    '#id',
    '#pw',
    '.btn_login',
    'form[action*="nidlogin.login"]',
    'iframe[src*="captcha"]',
    'iframe[title*="captcha"]',
  ],
  statusTextRegex: /자동저장|저장됨|저장 완료|저장되었습니다|임시저장/i,
  quoteRoot: '.se-component-quotation, [class*="quote"], [class*="quotation"], [data-type*="quote"]',
  quoteMenu: [
    '[data-name="quote"]',
    '[data-name="quotation"]',
    '[data-name="style"]',
    '[data-name="format"]',
    '[aria-label*="인용구"]',
    '[aria-label*="서식"]',
    '[aria-label*="스타일"]',
    '[title*="인용구"]',
    '[title*="서식"]',
    '[title*="스타일"]',
    'button:has-text("인용구")',
    '[role="button"]:has-text("인용구")',
  ],
  quote2Option: [
    '[data-name*="quote2"]',
    '[data-name*="quotation2"]',
    '[data-value*="quote2"]',
    '[data-style*="quote2"]',
    '[aria-label*="인용구2"]',
    'button:has-text("인용구2")',
    '[role="menuitem"]:has-text("인용구2")',
    'li:has-text("인용구2")',
    'button:has-text("인용구 2")',
  ],
  placeButton: [
    '[data-name="map"]',
    '[data-name="place"]',
    '[data-log="map"]',
    '[aria-label*="장소"]',
    '[aria-label*="지도"]',
    '[title*="장소"]',
    '[title*="지도"]',
    'button:has-text("장소")',
    'button:has-text("지도")',
  ],
  placePanel: [
    '[role="dialog"]',
    '[role="tabpanel"]',
    '.se-map-search-layer',
    '.se-place-search-layer',
    '.se-place-map-search',
    '.se-place-contents-wrap',
    '.map_search_layer',
    '[class*="place"][class*="layer"]',
    '[class*="map"][class*="layer"]',
  ],
  placeSearchInput: [
    'input[placeholder*="장소"]',
    'input[placeholder*="검색"]',
    'input[aria-label*="장소"]',
    '.se-map-search-input input',
    '.se-place-search-input input',
    '.map_search input[type="text"]',
  ],
  placeResultItem: [
    '.se-place-map-search-result-item',
    '.se-map-search-result-item',
    '.se-place-search-result li',
    '.map_search_list li',
    '.search_result_list li',
    '[class*="result"] li',
  ],
  placeResultLink: [
    '.se-place-map-search-result-link',
    '.se-map-search-result-link',
    '.se-place-map-search-result-item > a',
    '.se-place-search-result li a',
  ],
  placeAddButton: [
    '.se-place-map-search-result-item .se-place-add-button',
    '.se-place-add-button',
    'button:has-text("추가")',
    '[role="button"][aria-label*="추가"]',
    '[data-log*="add"]',
  ],
  placeConfirmButton: [
    '.se-popup-footer .se-popup-button-confirm',
    'footer.se-popup-footer .se-popup-button-confirm',
    '.se-popup-button-container .se-popup-button-confirm',
    '.se-popup-footer button[class*="primary"]',
    '.se-popup-footer [class*="primary"] button',
    'button:has-text("확인")',
    'button:has-text("첨부")',
    'button:has-text("삽입")',
    'button:has-text("적용")',
    '[role="button"][aria-label*="확인"]',
    '[role="button"][aria-label*="첨부"]',
    '[role="button"][aria-label*="삽입"]',
    '[role="button"][aria-label*="적용"]',
  ],
  placeCard: [
    '.se-component-map',
    '.se-component-place',
    '.se-component-content .se-map',
    '.se-component-content .se-place',
    '.se-component [class*="map"]',
    '.se-component [class*="place"]',
    '[data-module*="map"]',
    '[data-module*="place"]',
    '[data-type*="place"]',
  ],
};

export function selectorListToQuery(selectors: string[]): string {
  return selectors.join(', ');
}
